FROM python:3.7
COPY ./app /app
WORKDIR /app
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN apt-get update -y
RUN apt install libgl1-mesa-glx -y
RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["flask", "run"]